---
- name: Configure Ansible Controller
  hosts: ansible-lab-controller
  tasks:
  - name: Ensure latest Ansible versions
    become: yes
    ansible.builtin.package:
      name: 
      - ansible
      - git
      state: latest

- name: universal host configuration
  hosts: ansible_lab_hosts
  vars:
    ansible_become: True
  roles:
  - role: ansible-hardening
    vars:
      stig_version: rhel7
      security_enable_pwquality_password_set: yes
      security_password_max_lifetime_days: 90

- name: Configure DNS Server
  hosts: ansible-lab-host1
  vars:
    ansible_become: true
  tasks:
  - name: Install dnsmasq
    ansible.builtin.package:
      name: dnsmasq
      state: latest
    notify: Restart dnsmasq
  - name: set local hostname
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.4'
      line: '10.1.2.4 server1'
    notify: Restart dnsmasq
  - name: add hostserver2
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.5'
      line: '10.1.2.5 server2'
    notify: Restart dnsmasq  
  - name: add hostserver3
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.6'
      line: '10.1.2.6 server3'
    notify: Restart dnsmasq 
  - name: add controller
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.1\.4'
      line: '10.1.1.4 ansible-lab-controller'
    notify: Restart dnsmasq   
  - name: disable existing DNS
    ansible.builtin.service:
      name: systemd-resolved
      enabled: no
      state: stopped
  - name: Set dnsmasq configuration file
    copy:
      src: ./files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: '0644'
    notify: Restart dnsmasq
  
  handlers:
  - name : Restart dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      enabled: yes
      state: started
